-- 코드를 입력하세요
SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
JOIN (SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE MONTH(START_DATE) >= 8
      AND MONTH(START_DATE) <= 10
      AND YEAR(START_DATE) = 2022
      GROUP BY CAR_ID
      HAVING COUNT(*)>=5) AS M 
ON M.CAR_ID = C.CAR_ID
WHERE MONTH(START_DATE) >= 8
AND MONTH(START_DATE) <= 10
AND YEAR(START_DATE) = 2022
GROUP BY MONTH,CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH,CAR_ID DESC
